package videoeditor.jayshah.com.ffmpegvideoeditor;

import java.util.ArrayList;

public class LanguagesGoogle {


    static ArrayList<String> languageOriginalName = new ArrayList<String>();
    static ArrayList<String> languageCodeName = new ArrayList<String>();
    static ArrayList<String> languageEnglishName = new ArrayList<String>();

    public static ArrayList<String> getlanguageOriginalName() {
        languageOriginalName.add(" Afrikaans (Suid-Afrika)");
        languageOriginalName.add(" አማርኛ (ኢትዮጵያ)");
        languageOriginalName.add(" Հայ (Հայաստան)");
        languageOriginalName.add(" Azərbaycan (Azərbaycan)");
        languageOriginalName.add(" Bahasa Indonesia (Indonesia)");
        languageOriginalName.add(" Bahasa Melayu (Malaysia)");
        languageOriginalName.add(" বাংলা (বাংলাদেশ)");
        languageOriginalName.add(" বাংলা (ভারত)");
        languageOriginalName.add(" Català (Espanya)");
        languageOriginalName.add(" Čeština (Česká republika)");
        languageOriginalName.add(" Dansk (Danmark)");
        languageOriginalName.add(" Deutsch (Deutschland)");
        languageOriginalName.add(" English (Australia)");
        languageOriginalName.add(" English (Canada)");
        languageOriginalName.add(" English (Ghana)");
        languageOriginalName.add(" English (Great Britain)");
        languageOriginalName.add(" English (India)");
        languageOriginalName.add(" English (Ireland)");
        languageOriginalName.add(" English (Kenya)");
        languageOriginalName.add(" English (New Zealand)");
        languageOriginalName.add(" English (Nigeria)");
        languageOriginalName.add(" English (Philippines)");
        languageOriginalName.add(" English (South Africa)");
        languageOriginalName.add(" English (Tanzania)");
        languageOriginalName.add(" English (United States)");
        languageOriginalName.add(" Español (Argentina)");
        languageOriginalName.add(" Español (Bolivia)");
        languageOriginalName.add(" Español (Chile)");
        languageOriginalName.add(" Español (Colombia)");
        languageOriginalName.add(" Español (Costa Rica)");
        languageOriginalName.add(" Español (Ecuador)");
        languageOriginalName.add(" Español (El Salvador)");
        languageOriginalName.add(" Español (España)");
        languageOriginalName.add(" Español (Estados Unidos)");
        languageOriginalName.add(" Español (Guatemala)");
        languageOriginalName.add(" Español (Honduras)");
        languageOriginalName.add(" Español (México)");
        languageOriginalName.add(" Español (Nicaragua)");
        languageOriginalName.add(" Español (Panamá)");
        languageOriginalName.add(" Español (Paraguay)");
        languageOriginalName.add(" Español (Perú)");
        languageOriginalName.add(" Español (Puerto Rico)");
        languageOriginalName.add(" Español (República Dominicana)");
        languageOriginalName.add(" Español (Uruguay)");
        languageOriginalName.add(" Español (Venezuela)");
        languageOriginalName.add(" Euskara (Espainia)");
        languageOriginalName.add(" Filipino (Pilipinas)");
        languageOriginalName.add(" Français (Canada)");
        languageOriginalName.add(" Français (France)");
        languageOriginalName.add(" Galego (España)");
        languageOriginalName.add(" ქართული (საქართველო)");
        languageOriginalName.add(" ગુજરાતી (ભારત)");
        languageOriginalName.add(" Hrvatski (Hrvatska)");
        languageOriginalName.add(" IsiZulu (Ningizimu Afrika)");
        languageOriginalName.add(" Íslenska (Ísland)");
        languageOriginalName.add(" Italiano (Italia)");
        languageOriginalName.add(" Jawa (Indonesia)");
        languageOriginalName.add(" ಕನ್ನಡ (ಭಾರತ)");
        languageOriginalName.add(" ភាសាខ្មែរ (កម្ពុជា)");
        languageOriginalName.add(" ລາວ (ລາວ)");
        languageOriginalName.add(" Latviešu (latviešu)");
        languageOriginalName.add(" Lietuvių (Lietuva)");
        languageOriginalName.add(" Magyar (Magyarország)");
        languageOriginalName.add(" മലയാളം (ഇന്ത്യ)");
        languageOriginalName.add(" मराठी (भारत)");
        languageOriginalName.add(" Nederlands (Nederland)");
        languageOriginalName.add(" नेपाली (नेपाल)");
        languageOriginalName.add(" Norsk bokmål (Norge)");
        languageOriginalName.add(" Polski (Polska)");
        languageOriginalName.add(" Português (Brasil)");
        languageOriginalName.add(" Português (Portugal)");
        languageOriginalName.add(" Română (România)");
        languageOriginalName.add(" සිංහල (ශ්රී ලංකාව)");
        languageOriginalName.add(" Slovenčina (Slovensko)");
        languageOriginalName.add(" Slovenščina (Slovenija)");
        languageOriginalName.add(" Urang (Indonesia)");
        languageOriginalName.add(" Swahili (Tanzania)");
        languageOriginalName.add(" Swahili (Kenya)");
        languageOriginalName.add(" Suomi (Suomi)");
        languageOriginalName.add(" Svenska (Sverige)");
        languageOriginalName.add(" தமிழ் (இந்தியா)");
        languageOriginalName.add(" தமிழ் (சிங்கப்பூர்)");
        languageOriginalName.add(" தமிழ் (இலங்கை)");
        languageOriginalName.add(" தமிழ் (மலேசியா)");
        languageOriginalName.add(" తెలుగు (భారతదేశం)");
        languageOriginalName.add(" Tiếng Việt (Việt Nam)");
        languageOriginalName.add(" Türkçe (Türkiye)");
        languageOriginalName.add(" اردو (پاکستان)");
        languageOriginalName.add(" اردو (بھارت)");
        languageOriginalName.add(" Ελληνικά (Ελλάδα)");
        languageOriginalName.add(" Български (България)");
        languageOriginalName.add(" Русский (Россия)");
        languageOriginalName.add(" Српски (Србија)");
        languageOriginalName.add(" Українська (Україна)");
        languageOriginalName.add(" עברית (ישראל)");
        languageOriginalName.add(" العربية (إسرائيل)");
        languageOriginalName.add(" العربية (الأردن)");
        languageOriginalName.add(" العربية (الإمارات)");
        languageOriginalName.add(" العربية (البحرين)");
        languageOriginalName.add(" العربية (الجزائر)");
        languageOriginalName.add(" العربية (السعودية)");
        languageOriginalName.add(" العربية (العراق)");
        languageOriginalName.add(" العربية (الكويت)");
        languageOriginalName.add(" العربية (المغرب)");
        languageOriginalName.add(" العربية (تونس)");
        languageOriginalName.add(" العربية (عُمان)");
        languageOriginalName.add(" العربية (فلسطين)");
        languageOriginalName.add(" العربية (قطر)");
        languageOriginalName.add(" العربية (لبنان)");
        languageOriginalName.add(" العربية (مصر)");
        languageOriginalName.add(" فارسی (ایران)");
        languageOriginalName.add(" हिन्दी (भारत)");
        languageOriginalName.add(" ไทย (ประเทศไทย)");
        languageOriginalName.add(" 한국어 (대한민국)");
        languageOriginalName.add(" 國語 (台灣)");
        languageOriginalName.add(" 廣東話 (香港)");
        languageOriginalName.add(" 日本語（日本）");
        languageOriginalName.add(" 普通話 (香港)");
        languageOriginalName.add(" 普通话 (中国大陆)");
        return languageOriginalName;
    }

    public static ArrayList<String> getlanguageCodeName() {
        languageCodeName.add("af-ZA");
        languageCodeName.add("am-ET");
        languageCodeName.add("hy-AM");
        languageCodeName.add("az-AZ");
        languageCodeName.add("id-ID");
        languageCodeName.add("ms-MY");
        languageCodeName.add("bn-BD");
        languageCodeName.add("bn-IN");
        languageCodeName.add("ca-ES");
        languageCodeName.add("cs-CZ");
        languageCodeName.add("da-DK");
        languageCodeName.add("de-DE");
        languageCodeName.add("en-AU");
        languageCodeName.add("en-CA");
        languageCodeName.add("en-GH");
        languageCodeName.add("en-GB");
        languageCodeName.add("en-IN");
        languageCodeName.add("en-IE");
        languageCodeName.add("en-KE");
        languageCodeName.add("en-NZ");
        languageCodeName.add("en-NG");
        languageCodeName.add("en-PH");
        languageCodeName.add("en-ZA");
        languageCodeName.add("en-TZ");
        languageCodeName.add("en-US");
        languageCodeName.add("es-AR");
        languageCodeName.add("es-BO");
        languageCodeName.add("es-CL");
        languageCodeName.add("es-CO");
        languageCodeName.add("es-CR");
        languageCodeName.add("es-EC");
        languageCodeName.add("es-SV");
        languageCodeName.add("es-ES");
        languageCodeName.add("es-US");
        languageCodeName.add("es-GT");
        languageCodeName.add("es-HN");
        languageCodeName.add("es-MX");
        languageCodeName.add("es-NI");
        languageCodeName.add("es-PA");
        languageCodeName.add("es-PY");
        languageCodeName.add("es-PE");
        languageCodeName.add("es-PR");
        languageCodeName.add("es-DO");
        languageCodeName.add("es-UY");
        languageCodeName.add("es-VE");
        languageCodeName.add("eu-ES");
        languageCodeName.add("fil-PH");
        languageCodeName.add("fr-CA");
        languageCodeName.add("fr-FR");
        languageCodeName.add("gl-ES");
        languageCodeName.add("ka-GE");
        languageCodeName.add("gu-IN");
        languageCodeName.add("hr-HR");
        languageCodeName.add("zu-ZA");
        languageCodeName.add("is-IS");
        languageCodeName.add("it-IT");
        languageCodeName.add("jv-ID");
        languageCodeName.add("kn-IN");
        languageCodeName.add("km-KH");
        languageCodeName.add("lo-LA");
        languageCodeName.add("lv-LV");
        languageCodeName.add("lt-LT");
        languageCodeName.add("hu-HU");
        languageCodeName.add("ml-IN");
        languageCodeName.add("mr-IN");
        languageCodeName.add("nl-NL");
        languageCodeName.add("ne-NP");
        languageCodeName.add("nb-NO");
        languageCodeName.add("pl-PL");
        languageCodeName.add("pt-BR");
        languageCodeName.add("pt-PT");
        languageCodeName.add("ro-RO");
        languageCodeName.add("si-LK");
        languageCodeName.add("sk-SK");
        languageCodeName.add("sl-SI");
        languageCodeName.add("su-ID");
        languageCodeName.add("sw-TZ");
        languageCodeName.add("sw-KE");
        languageCodeName.add("fi-FI");
        languageCodeName.add("sv-SE");
        languageCodeName.add("ta-IN");
        languageCodeName.add("ta-SG");
        languageCodeName.add("ta-LK");
        languageCodeName.add("ta-MY");
        languageCodeName.add("te-IN");
        languageCodeName.add("vi-VN");
        languageCodeName.add("tr-TR");
        languageCodeName.add("ur-PK");
        languageCodeName.add("ur-IN");
        languageCodeName.add("el-GR");
        languageCodeName.add("bg-BG");
        languageCodeName.add("ru-RU");
        languageCodeName.add("sr-RS");
        languageCodeName.add("uk-UA");
        languageCodeName.add("he-IL");
        languageCodeName.add("ar-IL");
        languageCodeName.add("ar-JO");
        languageCodeName.add("ar-AE");
        languageCodeName.add("ar-BH");
        languageCodeName.add("ar-DZ");
        languageCodeName.add("ar-SA");
        languageCodeName.add("ar-IQ");
        languageCodeName.add("ar-KW");
        languageCodeName.add("ar-MA");
        languageCodeName.add("ar-TN");
        languageCodeName.add("ar-OM");
        languageCodeName.add("ar-PS");
        languageCodeName.add("ar-QA");
        languageCodeName.add("ar-LB");
        languageCodeName.add("ar-EG");
        languageCodeName.add("fa-IR");
        languageCodeName.add("hi-IN");
        languageCodeName.add("th-TH");
        languageCodeName.add("ko-KR");
        languageCodeName.add("cmn-Hant-TW");
        languageCodeName.add("yue-Hant-HK");
        languageCodeName.add("ja-JP");
        languageCodeName.add("cmn-Hans-HK");
        languageCodeName.add("cmn-Hans-CN");
        return languageCodeName;
    }

    public static ArrayList<String> getlanguageEnglishName() {
        languageEnglishName.add("Afrikaans (South Africa)");
        languageEnglishName.add("Amharic (Ethiopia)");
        languageEnglishName.add("Armenian (Armenia)");
        languageEnglishName.add("Azerbaijani (Azerbaijan)");
        languageEnglishName.add("Indonesian (Indonesia)");
        languageEnglishName.add("Malay (Malaysia)");
        languageEnglishName.add("Bengali (Bangladesh)");
        languageEnglishName.add("Bengali (India)");
        languageEnglishName.add("Catalan (Spain)");
        languageEnglishName.add("Czech (Czech Republic)");
        languageEnglishName.add("Danish (Denmark)");
        languageEnglishName.add("German (Germany)");
        languageEnglishName.add("English (Australia)");
        languageEnglishName.add("English (Canada)");
        languageEnglishName.add("English (Ghana)");
        languageEnglishName.add("English (United Kingdom)");
        languageEnglishName.add("English (India)");
        languageEnglishName.add("English (Ireland)");
        languageEnglishName.add("English (Kenya)");
        languageEnglishName.add("English (New Zealand)");
        languageEnglishName.add("English (Nigeria)");
        languageEnglishName.add("English (Philippines)");
        languageEnglishName.add("English (South Africa)");
        languageEnglishName.add("English (Tanzania)");
        languageEnglishName.add("English (United States)");
        languageEnglishName.add("Spanish (Argentina)");
        languageEnglishName.add("Spanish (Bolivia)");
        languageEnglishName.add("Spanish (Chile)");
        languageEnglishName.add("Spanish (Colombia)");
        languageEnglishName.add("Spanish (Costa Rica)");
        languageEnglishName.add("Spanish (Ecuador)");
        languageEnglishName.add("Spanish (El Salvador)");
        languageEnglishName.add("Spanish (Spain)");
        languageEnglishName.add("Spanish (United States)");
        languageEnglishName.add("Spanish (Guatemala)");
        languageEnglishName.add("Spanish (Honduras)");
        languageEnglishName.add("Spanish (Mexico)");
        languageEnglishName.add("Spanish (Nicaragua)");
        languageEnglishName.add("Spanish (Panama)");
        languageEnglishName.add("Spanish (Paraguay)");
        languageEnglishName.add("Spanish (Peru)");
        languageEnglishName.add("Spanish (Puerto Rico)");
        languageEnglishName.add("Spanish (Dominican Republic)");
        languageEnglishName.add("Spanish (Uruguay)");
        languageEnglishName.add("Spanish (Venezuela)");
        languageEnglishName.add("Basque (Spain)");
        languageEnglishName.add("Filipino (Philippines)");
        languageEnglishName.add("French (Canada)");
        languageEnglishName.add("French (France)");
        languageEnglishName.add("Galician (Spain)");
        languageEnglishName.add("Georgian (Georgia)");
        languageEnglishName.add("Gujarati (India)");
        languageEnglishName.add("Croatian (Croatia)");
        languageEnglishName.add("Zulu (South Africa)");
        languageEnglishName.add("Icelandic (Iceland)");
        languageEnglishName.add("Italian (Italy)");
        languageEnglishName.add("Javanese (Indonesia)");
        languageEnglishName.add("Kannada (India)");
        languageEnglishName.add("Khmer (Cambodia)");
        languageEnglishName.add("Lao (Laos)");
        languageEnglishName.add("Latvian (Latvia)");
        languageEnglishName.add("Lithuanian (Lithuania)");
        languageEnglishName.add("Hungarian (Hungary)");
        languageEnglishName.add("Malayalam (India)");
        languageEnglishName.add("Marathi (India)");
        languageEnglishName.add("Dutch (Netherlands)");
        languageEnglishName.add("Nepali (Nepal)");
        languageEnglishName.add("Norwegian Bokmål (Norway)");
        languageEnglishName.add("Polish (Poland)");
        languageEnglishName.add("Portuguese (Brazil)");
        languageEnglishName.add("Portuguese (Portugal)");
        languageEnglishName.add("Romanian (Romania)");
        languageEnglishName.add("Sinhala (Sri Lanka)");
        languageEnglishName.add("Slovak (Slovakia)");
        languageEnglishName.add("Slovenian (Slovenia)");
        languageEnglishName.add("Sundanese (Indonesia)");
        languageEnglishName.add("Swahili (Tanzania)");
        languageEnglishName.add("Swahili (Kenya)");
        languageEnglishName.add("Finnish (Finland)");
        languageEnglishName.add("Swedish (Sweden)");
        languageEnglishName.add("Tamil (India)");
        languageEnglishName.add("Tamil (Singapore)");
        languageEnglishName.add("Tamil (Sri Lanka)");
        languageEnglishName.add("Tamil (Malaysia)");
        languageEnglishName.add("Telugu (India)");
        languageEnglishName.add("Vietnamese (Vietnam)");
        languageEnglishName.add("Turkish (Turkey)");
        languageEnglishName.add("Urdu (Pakistan)");
        languageEnglishName.add("Urdu (India)");
        languageEnglishName.add("Greek (Greece)");
        languageEnglishName.add("Bulgarian (Bulgaria)");
        languageEnglishName.add("Russian (Russia)");
        languageEnglishName.add("Serbian (Serbia)");
        languageEnglishName.add("Ukrainian (Ukraine)");
        languageEnglishName.add("Hebrew (Israel)");
        languageEnglishName.add("Arabic (Israel)");
        languageEnglishName.add("Arabic (Jordan)");
        languageEnglishName.add("Arabic (United Arab Emirates)");
        languageEnglishName.add("Arabic (Bahrain)");
        languageEnglishName.add("Arabic (Algeria)");
        languageEnglishName.add("Arabic (Saudi Arabia)");
        languageEnglishName.add("Arabic (Iraq)");
        languageEnglishName.add("Arabic (Kuwait)");
        languageEnglishName.add("Arabic (Morocco)");
        languageEnglishName.add("Arabic (Tunisia)");
        languageEnglishName.add("Arabic (Oman)");
        languageEnglishName.add("Arabic (State of Palestine)");
        languageEnglishName.add("Arabic (Qatar)");
        languageEnglishName.add("Arabic (Lebanon)");
        languageEnglishName.add("Arabic (Egypt)");
        languageEnglishName.add("Persian (Iran)");
        languageEnglishName.add("Hindi (India)");
        languageEnglishName.add("Thai (Thailand)");
        languageEnglishName.add("Korean (South Korea)");
        languageEnglishName.add("Chinese, Mandarin (Traditional, Taiwan)");
        languageEnglishName.add("Chinese, Cantonese (Traditional, Hong Kong)");
        languageEnglishName.add("Japanese (Japan)");
        languageEnglishName.add("Chinese, Mandarin (Simplified, Hong Kong)");
        languageEnglishName.add("Chinese, Mandarin (Simplified, China)");
        return languageEnglishName;
}

}